export enum UnitsEnum {
    YEAR = 'Y',
    YEAR_ISO = 'o',
    MONTH = 'n',
    DAY = 'j',
    HOUR = 'G',
    MINUTE = 'i',
    SECOND = 's',
    MICRO = 'u',
    MICROSECOND = 'u',
    DAY_OF_WEEK = 'w',
    DAY_OF_WEEK_ISO = 'N',
    WEEK_OF_YEAR = 'W',
    DAYS_IN_MONTH = 't',
    TIMESTAMP = 'U',
    LATIN_MERIDIEM = 'a',
    LATIN_UPPER_MERIDIEM = 'A',
    ENGLISH_DAY_OF_WEEK = 'l',
    SHORT_ENGLISH_DAY_OF_WEEK = 'D',
    ENGLISH_MONTH = 'F',
    SHORT_ENGLISH_MONTH = 'M',
    TIMEZONE_ABBREVIATED_NAME = 'T',
    TZ_ABBR_NAME = 'T',
}
